PX6: Controller test for User,Group,Payment
projectx999/projectX9 pull request #18
Opened 2024-06-21 15:03 UTC by dev-manjit

- Controller test for User,Group, Payment
- Used UserDTO in all API request in User management APIs
- And related changes

2024-06-22 12:46 UTC, shansree1 requested changes

2024-06-24 21:21 UTC, dev-manjit commented on src/main/java/com/hydra/divideup/entity/Expense.java
> +    private String id;
mvn spotless:apply

2024-06-24 23:22 UTC, shansree1 commented on src/main/java/com/hydra/divideup/enums/Currency.java
> +  INR("Indian Rupee"),
Is this good to store in enum? we can have a DB/API in future since we will deal with multiple currency and we cannot hold all in enum as it will be very big.

2024-07-04 09:37 UTC, Bhargav-Chinnapottu commented on src/main/java/com/hydra/divideup/service/GroupService.java
> +    // Adding created user as member
There is no admin privilege for the user who created group

2024-07-06 16:41 UTC, Bhargav-Chinnapottu approved these changes

2024-10-25 19:25 UTC, shansree1 approved these changes

2024-10-25 19:30 UTC, merged